import type { RoomSnapshot } from "./onlineLobbySnapshot";

export function previewRoomSnapshot(overrides: Partial<RoomSnapshot> = {}): RoomSnapshot {
  return {
    roomCode: "auto-room",
    mode: "1v1",
    matchLength: "best-of-1",
    mapPick: "random",
    friendlyFire: false,
    selectedMapId: "ring-basin",
    selectedMapName: "Ringworks Basin",
    mapSeed: 51,
    targetScore: 1,
    terrainRevision: 1,
    terrainCraters: [],
    turnSequence: ["red-1", "blue-1"],
    turnDurationSeconds: 20,
    turnStartedAtMs: 1_000,
    turnEndsAtMs: 21_000,
    turnSecondsRemaining: 20,
    serverTimeMs: 1_000,
    turnAuthorityVersion: 1,
    lastAcceptedTurnIntentId: "",
    lastAcceptedTurnIntentType: "",
    lastAcceptedTurnIntentVehicleId: "",
    lastAcceptedTurnIntentSessionId: "",
    lastShotId: "",
    lastShotShooterVehicleId: "",
    lastShotShooterSessionId: "",
    lastShotOriginX: 0,
    lastShotOriginY: 0,
    lastShotAngle: 0,
    lastShotPower: 0,
    lastShotFacing: 1,
    lastShotWind: 0,
    lastShotImpactX: 0,
    lastShotImpactY: 0,
    lastShotDirectHitVehicleId: "",
    lastShotTargetVehicleId: "",
    lastShotDamage: 0,
    lastShotTargetHpBefore: 0,
    lastShotTargetHpAfter: 0,
    lastShotTurnNumber: 0,
    lastShotTurnAuthorityVersion: 0,
    lastShotServerTimeMs: 0,
    hostSessionId: "red-session",
    spectatorSessionIds: [],
    phase: "combat-preview",
    status: "Round 1 started.",
    roundNumber: 1,
    turnNumber: 1,
    wind: 4,
    activeVehicleId: "red-1",
    winnerTeam: "",
    lastRewardLog: "",
    players: [
      {
        sessionId: "red-session",
        displayName: "Red",
        team: "red",
        role: "host",
        joinOrder: 1,
        ready: true,
        tokens: 0,
        equippedNameplate: "Canyon Rookie",
        inventory: ["Canyon Rookie"],
      },
      {
        sessionId: "blue-session",
        displayName: "Blue",
        team: "blue",
        role: "player",
        joinOrder: 2,
        ready: true,
        tokens: 0,
        equippedNameplate: "Canyon Rookie",
        inventory: ["Canyon Rookie"],
      },
    ],
    slots: [],
    vehicles: [
      {
        vehicleId: "red-1",
        seatId: "red-1",
        ownerSessionId: "red-session",
        displayName: "Red / Nova",
        team: "red",
        characterId: "nova",
        className: "Bunger Rig",
        hp: 100,
        maxHp: 100,
        alive: true,
        defeatReason: "",
        x: 385,
        y: 0,
        moveUnits: 10,
        facing: 1,
        angle: 47,
      },
      {
        vehicleId: "blue-1",
        seatId: "blue-1",
        ownerSessionId: "blue-session",
        displayName: "Blue / Vesper",
        team: "blue",
        characterId: "vesper",
        className: "Glitch Rover",
        hp: 60,
        maxHp: 100,
        alive: true,
        defeatReason: "",
        x: 1995,
        y: 0,
        moveUnits: 10,
        facing: -1,
        angle: 133,
      },
    ],
    ...overrides,
  };
}
