import type { RoomSnapshot } from "./onlineLobbySnapshot";

export function previewRoomSnapshot(overrides: Partial<RoomSnapshot> = {}): RoomSnapshot {
  return {
    roomCode: "auto-room",
    mode: "1v1",
    hostSessionId: "red-session",
    spectatorSessionIds: [],
    phase: "combat-preview",
    status: "Round 1 started.",
    roundNumber: 1,
    turnNumber: 1,
    wind: 4,
    activeVehicleId: "red-1",
    winnerTeam: "",
    lastRewardLog: "",
    players: [
      {
        sessionId: "red-session",
        displayName: "Red",
        team: "red",
        role: "host",
        joinOrder: 1,
        ready: true,
        tokens: 0,
        equippedNameplate: "Canyon Rookie",
        inventory: ["Canyon Rookie"],
      },
      {
        sessionId: "blue-session",
        displayName: "Blue",
        team: "blue",
        role: "player",
        joinOrder: 2,
        ready: true,
        tokens: 0,
        equippedNameplate: "Canyon Rookie",
        inventory: ["Canyon Rookie"],
      },
    ],
    slots: [],
    vehicles: [
      {
        vehicleId: "red-1",
        ownerSessionId: "red-session",
        displayName: "Red / Nova",
        team: "red",
        className: "Bunger Rig",
        hp: 100,
        maxHp: 100,
        alive: true,
        x: 385,
        y: 0,
        angle: 47,
      },
      {
        vehicleId: "blue-1",
        ownerSessionId: "blue-session",
        displayName: "Blue / Vesper",
        team: "blue",
        className: "Glitch Rover",
        hp: 60,
        maxHp: 100,
        alive: true,
        x: 1995,
        y: 0,
        angle: 133,
      },
    ],
    ...overrides,
  };
}
